app/workers/forms.py
from quart_auth import current_user
from re import sub
from werkzeug.security import generate_password_hash
from wtforms import Form, PasswordField, SelectField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Regexp

from app import db
from ..utils.utils import escape
# from ..utils.form import Form


def set_worker_data(form):
  return {'worker': sub('[^a-zA-Z0-9 \]\[{}()"'';:,.&|?!~#$%<>=/*+-]+', '-', escape(form.worker.data)),
          'email': form.email.data.strip(),
          'phone': sub('[^0-9+-]+', '-', form.phone.data),
          'address': sub('[^a-zA-Z0-9 \]\[{}()"'';:,.&|?!~#$%<>=/*+-]+', '-', escape(form.address.data)),
          'lat': form.lat.data,
          'lon': form.lon.data,
          'password': generate_password_hash(form.password.data)}


class LoginForm(Form):
  email = StringField('Email', validators=[DataRequired(), Email(message='Email inválido.')])
  password = PasswordField('Contraseña', validators=[DataRequired(message='Por favor llene este campo.')])
  submit = SubmitField('Ingreso')


class ResetForm(Form):
  email = StringField('Email', validators=[DataRequired(), Email(message='Email inválido.')])
  submit = SubmitField('Enviar')


class WorkerForm(Form):
  worker = StringField('Usuario', validators=[DataRequired(message='Por favor llene este campo.')])
  email = StringField('Email', validators=[DataRequired(), Email(message='Email inválido.')])
  phone = StringField('Telefono', validators=[DataRequired(message='Por favor llene este campo.')])
  address = StringField('Direccion', validators=[DataRequired(message='Por favor llene este campo.')])
  lat = StringField('Latitud', validators=[DataRequired(), Regexp('^[-+]?[0-9]*\.?[0-9]+$', message='Número inválido.')])
  lon = StringField('Longitud', validators=[DataRequired(), Regexp('^[-+]?[0-9]*\.?[0-9]+$', message='Número inválido.')])
  password = PasswordField('Contraseña', validators=[DataRequired(message='Por favor llene este campo.'),
                                          EqualTo('confirm_password', message='Clave debe ser igual a su confirmación.')])
  confirm_password = PasswordField('Confirmar Clave', validators=[DataRequired()])
  submit = SubmitField('Registrarse', render_kw={'class':'btn btn-primary'})


async def check_worker(worker):
  row = db.one("SELECT id FROM workers WHERE worker=%s", (worker, ))
  if row and (not await current_user.is_authenticated or row[0] != int(await current_user.id)):
    raise Exception('Usuario ya esta en uso!')


async def check_email(email):
  row = db.one("SELECT id FROM workers WHERE email=%s", (email, ))
  if row and (not await current_user.is_authenticated or row[0] != int(await current_user.id)):
    raise Exception('Email ya esta en uso!')

app/workers/__init__.py
from quart import Blueprint

workers = Blueprint('workers', __name__, template_folder='')

from . import views
from .views import get_settings_menu

app/workers/views.py
from json import dumps
from quart import current_app, flash, redirect, request, render_template, session, url_for  # abort,
from quart_auth import current_user, login_required, login_user, logout_user
from random import choice
from re import sub
from string import ascii_letters, digits
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, xc
from . import workers
from .forms import LoginForm, ResetForm, WorkerForm, set_worker_data, check_worker, check_email
# from ..pgvega.views import get_reports_menu
# from ..notebooks.views import get_notebooks_menu
from ..utils.admin import User, check_admin, check_user
from ..utils.utils import escape, unescape, JsonEncoder, send_email, paginate


def get_settings_menu(u_admin, u_access):
  admin = [{"url": "workers.workers_handler", "name": "Usuarios"},
           {"url": "pgvega.reports", "name": "Reportes"},
           {"url": "pgvega.alerts", "name": "Alertas"},
           {"url": "notebooks.notebooks_handler", "name": "Notebooks"}] if u_admin else []
  forms = filter(lambda x: u_admin or url_for(x['url']) in u_access,
                 [{"url": "workers.calendar", "name": "Calendario"},
                  {"url": "workers_chats.get_chats", "name": "Chat"},
                  {"url": "workers.get_account", "name": "Usuario"}]) 
  return {"code": "settings", "title": "Ajustes",
          "forms": list(forms)+admin, "reports": [], "notebooks": []}


######################## START ########################
def set_session(activity_url):
  if activity_url != '' and activity_url != 'favicon.ico':
    activity = db.one("""SELECT CURRENT_SCHEMA(), 'activity_' || id, activity, logo
                         FROM public.activities WHERE url=%s;""", (activity_url, ))
    if activity and activity[0] != activity[1]:
      db.execute("SET search_path TO %s;", (activity[1], ))
      session['activity_url'] = activity_url
      session['schema'] = activity[1]
      session['activity'] = activity[2]
      session['logo'] = activity[3]


@workers.route('/<activity_url>')
@db.wrapper
async def home(activity_url='granja'):
  set_session(activity_url)
  return await render_template('templates/index.html', title="Inicio", activity_url=activity_url)


@workers.route('/<activity_url>/login', methods=['GET', 'POST'])
@db.wrapper
async def login(activity_url):
  set_session(activity_url)
  form = LoginForm(await request.form)
  if request.method == 'POST' and form.validate():
    email = form.email.data.strip()
    user = db.one("SELECT id, worker, password FROM workers WHERE email=%s", (email, ), as_dict=True)
    if not user:
      await flash('Email mal escrito o usuario no ha creado cuenta!')
      # return redirect(url_for('workers.register'))
    elif not check_password_hash(user['password'], form.password.data):
      await flash('Contraseña invalida.')
    else:
      login_user(User(user['id']))
      if not await current_user.is_authenticated:
        db.execute("UPDATE workers SET logged=NOW() WHERE id=%s;", (user['id'], ))
        db.commit()
      u_admin = await current_user.admin
      u_access = await current_user.access
      session['menu'] = [fn(u_admin, u_access) for fn in current_app.menu]
      await flash('Hola, %s!' % unescape(user['worker']))
      return redirect(url_for('workers.calendar'))

  return await render_template('templates/login.html', title='Ingreso', form=form, activity_url=activity_url)


@workers.route('/<activity_url>/reset_password', methods=['GET', 'POST'])
@db.wrapper
async def reset_password(activity_url):
  set_session(activity_url)
  rq = await request.form 
  form = ResetForm(rq)
  if request.method == 'POST' and form.validate() and xc.verify(rq, request.remote_addr):
    email = form.email.data.strip()
    user = db.one("SELECT id FROM workers WHERE email=%s", (email, ), as_dict=True)
    if user:
      password = ''.join(choice(ascii_letters + digits) for n in range(6))
      send_email(email, 'Granja Libre - nueva contraseña',
                 '\n\n' + \
                 'Contraseña: ' + \
                 password + \
                 '\n\n' + \
                 request.url_root[:-1] + url_for('workers.login', activity_url=activity_url))
      db.execute("UPDATE workers SET password=%s WHERE id=%s;", (generate_password_hash(password), user['id']))
      db.commit()
      await flash('Nueva contraseña enviada a: %s!' % email)
      return redirect(url_for('workers.login', activity_url=activity_url))
    else:
      await flash('No existe un usuario con este email: %s!' % email)
      return redirect(url_for('workers.login', activity_url=activity_url))  # redirect(url_for('workers.register', activity_url=activity_url))

  return await render_template('templates/reset_password.html', title='Nueva Contraseña',
                               form=form, activity_url=activity_url)


# @workers.route('/<activity_url>/register', methods=['GET', 'POST'])
# async def register(activity_url):
#   set_session(activity_url)
#   rq = await request.form 
#   form = WorkerForm(rq)
#   if request.method == 'POST' and form.validate() and xc.verify(rq, request.remote_addr):
#     data = set_worker_data(form)
#     await check_worker(data['worker'])
#     await check_email(data['email'])
#     db.execute("""INSERT INTO workers
#                   VALUES (DEFAULT, %(worker)s, %(email)s, %(phone)s, %(address)s,
#                           %(lat)s, %(lon)s, %(password)s, FALSE, NULL, NULL, NULL, NOW());""", data)
#     db.commit()
#     await flash('Se ha registrado correctamente! Ahora puede iniciar sesión.')
#
#     return redirect(url_for('workers.login', activity_url=activity_url))
#
#   return await render_template('templates/register.html', form=form, title='Registro', activity_url=activity_url)


######################## ACCOUNT ########################
@workers.route('/granja/worker/account', methods=['GET', 'POST'])
@login_required
@check_user
@db.wrapper
async def get_account():
  u_id = await current_user.id
  user = db.one("SELECT id, worker, email, phone, address, lat, lon FROM workers WHERE id=%s;",
                (u_id, ), as_dict=True)
  form = WorkerForm(await request.form)
  if request.method == 'POST' and form.validate():
    data = set_worker_data(form)
    data['id'] = u_id
    await check_worker(data['worker'])
    await check_email(data['email'])
    db.execute("""UPDATE workers
                  SET worker=%(worker)s, email=%(email)s, phone=%(phone)s, address=%(address)s, lat=%(lat)s,
                      lon=%(lon)s, password=%(password)s WHERE id=%(id)s;""", data)
    db.commit()
    await flash('Ha actualizado su información correctamente!')
  else:
    user['worker'] = unescape(user['worker'])
    user['address'] = unescape(user['address'])
    form = WorkerForm(**user)
  # if delete worker
  #   save_path = "{root}/{folder}".format(root=current_app.root_path + current_app.config['PRODUCT_IMAGES_PATH'],
  #                                        folder="items")
  #   imgs = db.all("SELECT img FROM products_images WHERE product_id=%s", (rq['id'], ))
  #   for img in imgs:
  #     remove("{path}/{file}.JPG".format(path=save_path, file=img[0]))
  #     remove("{path}/{file}_thumb.JPG".format(path=save_path, file=img[0]))

  # workermap = Map(
  #   identifier="view-side",
  #   lat=user['lat'],
  #   lng=user['lon'],
  #   markers=[(user['lat'], user['lon'])],
  #   style="width:100%;height:700px;",
  #   zoom=9
  # )

  # reports=get_reports_menu('^account_'), notebooks=get_notebooks_menu('^account_'), workermap=workermap
  return await render_template('templates/account.html', title='Cuenta', form=form)


@workers.route('/granja/worker/logout')
@login_required
@check_user
@db.wrapper
async def logout():
  logout_user()
  await flash('Ha cerrado la sesión correctamente.')

  return redirect(url_for('workers.login', activity_url=session['activity_url']))


######################## CALENDAR ########################
@workers.route('/granja/worker/calendar')
@login_required
@check_user
@db.wrapper
async def calendar():
  return await render_template('templates/calendar.html', title="Calendario")


@workers.route('/granja/worker/calendar_get', methods=['POST'])
@login_required
@check_user
@db.wrapper
async def get_calendar():
  rq = await request.form
  u_worker = await current_user.worker
  rows = db.all("""
    WITH events AS (SELECT * FROM calendar
                    WHERE start_date>=%s AND start_date<=%s OR
                          end_date>=%s AND end_date<=%s)
    SELECT id, color, title AS name, start_date AS startdate, end_date AS enddate
    FROM events WHERE worker=%s OR color IS NULL;""",
    (rq['start_date'], rq['end_date'], rq['start_date'], rq['end_date'], u_worker), as_dict=True)
  return dumps(rows, cls=JsonEncoder)


@workers.route('/granja/worker/calendar_set', methods=['POST'])
@login_required
@check_user
@db.wrapper
async def set_calendar():
  rq = await request.form
  u_worker = await current_user.worker
  rows = db.all("""
    INSERT INTO calendar VALUES(DEFAULT, %s, %s, %s, %s, %s)
    RETURNING id, color, title AS name, start_date AS startdate, end_date AS enddate;""",
    (u_worker, rq['color'], rq['title'], rq['start_date'], rq['end_date']), as_dict=True)
  db.commit()
  return dumps(rows, cls=JsonEncoder)


######################## WORKERS ########################
def get_workers_data(rq):
  params = {'filter':'{}', 'sort_col':'1', 'sort_dir':'ASC', 'lines':30,
            'page':int(rq['page']) if request.method == 'POST' else 1}
  return paginate(db, params, """
    SELECT id, unescape(worker) AS worker, email, phone, unescape(address) AS address,
           lat, lon, admin, created, logged, blocked, readonly, access
    FROM workers""")


@workers.route('/granja/workers/list')
@login_required
@check_admin
@db.wrapper
async def workers_handler():
  rq = await request.form
  # reports=get_reports_menu('^workers_'), notebooks=get_notebooks_menu('^workers_')

app/workers/templates/account.html
{% import "bootstrap_wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Cuenta{% endblock %}
{% block body %}
<div>
  <!--ul class="nav justify-content-end">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reportes</a>
      <div class="dropdown-menu dropdown-menu-end">
        {% for x in reports %}
        <a class="dropdown-item" href="{# url_for('pgvega.get_report', report_id=x['id']) #}">
          {{ x['title'] }}
        </a>
        {% endfor %}
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Notebooks</a>
      <div class="dropdown-menu dropdown-menu-end">
        {% for x in notebooks %}
        <a class="dropdown-item" href="{{ url_for('notebooks.get_notebook', notebook_id=x['id']) }}">
          {{ x['title'] }}
        </a>
        {% endfor %}
      </div>
    </li>
  </ul-->

  <h2>Cuenta</h2>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

      {% include 'templates/worker.html' %}

    </div>
    <div class="col-md-2"></div>
  </div>

  <br>

  {# workermap.html #}

</div>
{% endblock %}

{% block script %}

{# workermap.js #}

{% endblock %}

app/workers/templates/calendar.html
{% extends "base.html" %}
{% block title %}Ingreso{% endblock %}
{% block body %}
<div>

  <div class="monthly">
    <div id="calendar" class="monthly"></div>
  </div>

</div>
{% endblock %}

{% block script %}
<script>
  // CALENDAR
  $("#calendar").monthly({
    mode: "event",
    weekStart: "Mon",
    monthNames: ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
    dayNames: ["DOM","LUN","MAR","MIE","JUE","VIE","SAB"],
    eventList: false,
    dataType: "json",
    data: function(month, year, callback) {
      var pd = new FormData();
      pd.append("action", "select_calendar");
      pd.append("start_date", new Date(year, month-1, 1).toSql());
      pd.append("end_date", new Date(year, month, 1).toSql());
      request('{{ url_for("workers.get_calendar") }}', pd, callback);
    },
    dayClick: function(day, month, year, callback){
      var title = prompt("Nuevo evento:"),
          date = new Date(year, month-1, day).toSql();
      if (title) {
        var pd = new FormData();
        pd.append("action", "select_calendar");
        pd.append("color", "red");
        pd.append("title", title);
        pd.append("start_date", date);
        pd.append("end_date", date);
        request('{{ url_for("workers.set_calendar") }}', pd, callback);
      }
    }
  });
</script>
{% endblock %}

app/workers/templates/index.html
{% extends "base.html" %}
{% block title %}Inicio{% endblock %}
{% block body %}
  <div class="p-5" style="background:#e9ecef">
    <div class="container mt-5">
      <h1 class="display-2">Granja Libre</h1>
      <p>Es un Sofware Libre para el manejo Reproductivo y Productivo de una o muchas Granjas.  Se puede modificar los Parametros Reprodcutivos, Razas, causas de Muerte, entre otras variables, lo cual permite adaptar el programa a cualquier especie animal, por ejemplo: porcinos, bovinos, equinos, caprinos, ovinos, conejos o aves. Tambien se adapta segun el tipo de produccion: leche, carnicos o doble proposito.</p>
      <p>
        <a class="btn btn-success btn-lg" href="{{ url_for('workers.login', activity_url=activity_url) }}" role="button">Ingresar »</a>
      </p>
    </div>
  </div>

  <div class="container mt-5">

    <div class="row">
      <div class="col-md-4">
        <h2>Reproduccion</h2>
        <p>Desde el inicio esta pensado en el manejo de muchas granjas, en las cuales haya intercambio de genetica... de esta forma el arbol genealogico se mantiene sin importar en la granja que se encuentre el animal.  Se pueden evaluar mas de 50 parametros reproductivos, inventarios, datos medicos, entre otros.  La informacion se analiza mediante reportes o notebooks(permiten el uso de programas de inteligencia artificial).</p>
        <!--p><a class="btn btn-secondary" href="{# url_for('start.register', activity_url=activity_url) #}" role="button">Más información »</a></p-->
      </div>
      <div class="col-md-4">
        <h2>Produccion</h2>
        <p>Principalmente este modulo es para inventarios (animales y alimentos) y consumos.  Su interfaz grafica permite facilmente actualizar la informacion desde un celular.  Con los graficos se puede identificar rapidamente problemas u oportunidades de mejora.</p>
        <!--p><a class="btn btn-secondary" href="{# url_for('start.register', activity_url=activity_url) #}" role="button">Más información »</a></p-->
      </div>
      <div class="col-md-4">
        <h2>Software Libre</h2>
        <p>Es un programa realizado con Software Libre. Como base de datos: Postgresql, lenguaje de servidor: Python e interfaz de cliente: HTML5 (Javascript, HTML, CSS). Se puede descargar gratituamente en GitHub.</p>
        <p><a class="btn btn-secondary" href="https://github.com/wagnerc4/granjalibre" role="button">Descargar »</a></p>
      </div>
    </div>

  </div> <!-- /container -->
{% endblock %}

app/workers/templates/login.html
{% import "bootstrap_wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Ingreso{% endblock %}
{% block body %}
<div class="container">
  <br/>
  <br/>
  <br/>

  <form action="" method="post" class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">Ingreso a cuenta</h1>
    {# form.csrf_token() #}
    <input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}">
    {{ wtf.form_field(form.email, class='form-control', placeholder='Email . . .', autocapitalize='off') }}
    {{ wtf.form_field(form.password, class='form-control', placeholder='Contraseña . . .') }}
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('workers.reset_password', activity_url=activity_url) }}">Olvidó Contraseña?</a>
      </li>
    </ul>
    <button type="submit" class="w-100 btn btn-lg btn-success">Ingreso</button>
    <!--a href="{# url_for('workers.register', activity_url=activity_url) #}" role="button" class="btn btn-outline-success w-100 mt-2">Crear Cuenta</a-->
  </form>

</div>
{% endblock %}

app/workers/templates/register.html
{% import "bootstrap_wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Registro{% endblock %}
{% block body %}
<div class="container">
  <br/>
  <div class="row">
    <div class="col-md-8">
      <br/>

      {% include 'templates/worker.html' %}

    </div>
    <div class="col-md-4">
      <!--br/>

      <h1>Como Funciona:</h1>
      <p>Con la aplicación web el productor podrá: ingresar productos, actualizar precios e inventario disponible, organizar los pedidos y consultar estadísticas sobre sus ventas.</p>
      <p>Primero la persona debe registrarse, luego ingresar sus productos, para una posterior revisión y aprobación por parte de Huerta CR. Asi los clientes podrán iniciar con el ingreso pedidos.</p>
      <p>Cuando se resive un pedido, el productor se pondrá en contacto con el cliente para acordar el pago (efectivo, transferencia, etc...) y la entrega de los articulos (se envian al cliente o se retiran en algun lugar establecido).</p-->

    </div>
  </div>
</div>
{% endblock %}

app/workers/templates/reset_password.html
{% import "bootstrap_wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Nueva Contraseña{% endblock %}
{% block body %}
<div class="container">
  <br/>
  <br/>
  <br/>

  <form action="" method="post" class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">Nueva Contraseña</h1>
    {# form.csrf_token() #}
    <input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}">
    {{ wtf.form_field(form.email, class='form-control', placeholder='Email . . .', autocapitalize='off') }}
    {{ xcaptcha }}
    <button type="submit" class="w-100 btn btn-lg btn-success">Enviar</button>
  </form>

</div>
{% endblock %}

app/workers/templates/worker.html
<form action="" method="post" class="form" role="form">
  {# form.csrf_token() #}
  <input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}">
  {{ wtf.form_field(form.worker, class='form-control', placeholder='Usuario . . .') }}
  <!--div class="row">
    <div class="form-group col-md-6">
      {# wtf.form_field(form.worker, class='form-control', placeholder='Usuario . . .') #}
    </div>
    <div class="form-group col-md-6">
      {# wtf.form_field(form.occupation, class='form-control') #}
    </div>
  </div-->
  <div class="row">
    <div class="form-group col-md-6">
    {{ wtf.form_field(form.email, class='form-control', placeholder='Email . . .', autocapitalize='off') }}
    </div>
    <div class="form-group col-md-6">
    {{ wtf.form_field(form.phone, class='form-control', placeholder='Teléfono . . .') }}
    </div>
  </div>
  {{ wtf.form_field(form.address, class='form-control', placeholder='Dirección . . .') }}
  <div class="row">
    <div class="form-group col-md-6">
    {{ wtf.form_field(form.lat, class='form-control', placeholder='Latitud . . .') }}
    </div>
    <div class="form-group col-md-6">
    {{ wtf.form_field(form.lon, class='form-control', placeholder='Longitud . . .') }}
    </div>
  </div>
  <div class="row mb-4">
    <button id="ubication_btn" class="btn btn-warning ms-3" onclick="showPosition();">Obtener ubicacion</button>
    <span id="ubication_result" class="ms-3"></span>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
    {{ wtf.form_field(form.password, class='form-control', placeholder='Clave . . .') }}
    </div>
    <div class="form-group col-md-6">
    {{ wtf.form_field(form.confirm_password, class='form-control', placeholder='Clave . . .') }}
    </div>
  </div>
  {% if not current_user.is_authenticated %}
    {{ xcaptcha }}
  {% endif %}
  <button type="submit" class="btn btn-success">Actualizar</button>
</form>
<script>
    var result;
    
    function showPosition() {
        // Store the element where the page displays the result
        result = document.getElementById("ubication_result");
        
        // If geolocation is available, try to get the visitor's position
        if(navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(successCallback, errorCallback);
            result.innerHTML = "Obteniendo la ubicacion...";
        } else {
            alert("Disculpe, su navegador no soporta HTML5 geolocalizacion.");
        }
    };
    
    // Define callback function for successful attempt
    function successCallback(position) {
        result.innerHTML = "Su ubicacion actual es: (" + "Latitud: " + position.coords.latitude + ", " + "Longitud: " + position.coords.longitude + ")";
        document.getElementById("lat").value = position.coords.latitude;
        document.getElementById("lon").value = position.coords.longitude;
    }
    
    // Define callback function for failed attempt
    function errorCallback(error) {
        if(error.code == 1) {
            result.innerHTML = "Su navegador no tiene permiso para compartir su ubicacion.";
        } else if(error.code == 2) {
            result.innerHTML = "Por favor intente de nuevo.";
            console.log("The network is down or the positioning service can't be reached.");
        } else if(error.code == 3) {
            result.innerHTML = "Por favor intente de nuevo.";
            console.log("The attempt timed out before it could get the location data.");
        } else {
            result.innerHTML = "Por favor intente de nuevo.";
            console.log("Geolocation failed due to unknown error.");
        }
    }
</script>