app/pgvega/__init__.py
from quart import Blueprint

pgvega = Blueprint('pgvega', __name__, template_folder='')

from . import views

app/pgvega/views.py
from json import dumps, loads
from quart import make_response, render_template, request, session, url_for
from quart_auth import current_user, login_required

from app import db
from . import pgvega
from .report_utils import set_content, set_pdf, set_header_html, set_report_html
from ..utils.admin import check_admin, check_user
from ..utils.utils import JsonEncoder, escape


############################# REPORTS #############################
def get_reports_menu(code):
  # WHERE code ~ '^(forms|resumens|accounting|settings)((?!_subquery).)+$'
  return db.all("""SELECT code, title FROM querys WHERE code ~ %s AND code ~ '^(.+)((?!_subquery).)+$'
                   ORDER BY code;""", (code, ), as_dict=True)


def get_schema_titles():
  return {"schema": db.all("""SELECT c.relname AS table,
                                     (SELECT STRING_AGG(attname, ',') FROM pg_catalog.pg_attribute
                                      WHERE attrelid=c.oid AND attnum > 0 AND NOT attisdropped) AS columns
                              FROM pg_catalog.pg_class c
                              JOIN pg_catalog.pg_namespace n ON c.relnamespace=n.oid
                              WHERE c.relkind IN ('r', 'v') AND n.nspname=(SELECT CURRENT_SCHEMA)
                              ORDER BY c.relname;""", as_dict=True),
          "titles": db.all("""SELECT code, unescape(title) AS title, MAX(LENGTH(code)) OVER() AS l
                              FROM querys ORDER BY code;""", as_dict=True)}


def get_report_data(code, rq, pdf=False):
  content = []
  title, defs = tuple(db.one("SELECT title, defs FROM querys WHERE code=%s;", (code, )))
  defs = loads(defs.replace('\\\\', '\n'))
  codes = defs[0]['defs'] if len(defs) > 0 and 'type' in defs[0] and defs[0]['type'] == 'group' else [code]
  rows = db.all("SELECT query, defs, title FROM querys WHERE code IN %s ORDER BY code;", (tuple(codes), ))
  for row in rows:
    data = db.all(row[0].replace('\\\\', '\n'), rq)
    defs = loads(row[1].replace('\\\\', '\n'))
    if len(defs) < 1:
      cols = db.description()
      defs = [{"type":"table", "defs":[{"head":c} for c in cols]}]
    tmp = set_content(defs, data, pdf)
    if len(rows) > 1: tmp[0]['title'] = row[2]
    content = content + tmp
  rs = {"code": code, "title": title, "content": content}
  return rs if pdf else dumps(rs, cls=JsonEncoder)


@pgvega.route('/get_report/<code>', methods=['GET', 'POST'])
@login_required
@check_user
@db.wrapper
async def get_report(code):
  if request.method == 'GET':
    row = db.one("""
      SELECT title,
             query LIKE %s AS d1,
             query LIKE %s AS d2,
             query LIKE %s AS g1,
             query LIKE %s AS g2,
             query LIKE %s AS v,
             query LIKE %s AS c
      FROM querys WHERE code=%s;""",
      ('%%%%(d1)s%%', '%%%%(d2)s%%', '%%%%(g1)s%%', '%%%%(g2)s%%', '%%%%(v)s%%', '%%%%(c)s%%', code), as_dict=True)
    if not row:
      raise Exception('Error: reporte no ingresado!')
    return await render_template('templates/report.html', code=code, data=dumps(row, cls=JsonEncoder))
  else:
    rq = await request.form
    return get_report_data(code, rq, pdf=False)


@pgvega.route('/get_report_pdf/<code>', methods=['POST'])
@login_required
@check_user
@db.wrapper
async def get_report_pdf(code):
  rq = await request.form
  try:
    activity = db.one("""SELECT unescape(activity) FROM public.activities
                         WHERE id=REPLACE((SELECT CURRENT_SCHEMA), 'activity_', '')::INT;""")[0]
    pdf = set_pdf(set_header_html('Granja Libre - ' + activity),
                  set_report_html(get_report_data(code, rq, pdf=True), rq['params']))
    rs = await make_response(pdf)
    rs.content_type = 'application/pdf'
    rs.headers["Content-Disposition"] = "filename=%s.pdf" % code
  except Exception as e:
    rs = await make_response("db error -> " + str(e), 500)
  return rs


#######################################################################
@pgvega.route('/admin-reports/build')
@login_required
@check_admin
@db.wrapper
async def reports():
  return await render_template('templates/reports.html', title="Reportes",
                               schema_titles=get_schema_titles())


@pgvega.route('/admin-reports/query_get_def', methods=['POST'])
@login_required
@check_admin
@db.wrapper
async def get_query_def():
  rq = await request.form
  return dumps(db.one("SELECT * FROM querys WHERE code=%s;", (rq['code'], )), cls=JsonEncoder)


@pgvega.route('/admin-reports/query_set', methods=['POST'])
@login_required
@check_admin
@db.wrapper
async def set_query():
  rq = await request.form
  if rq['action'] == 'insert':
    db.execute("INSERT INTO querys VALUES (DEFAULT, %s, %s, %s, %s);",
               (rq['query'], rq['defs'], rq['code'], escape(rq['title'])))
  elif rq['action'] == 'update':
    db.execute("UPDATE querys SET query=%s, defs=%s, title=%s WHERE code=%s;",
               (rq['query'], rq['defs'], escape(rq['title']), rq['code']))
  else:
    db.execute("DELETE FROM querys WHERE code=%s;", (rq['code'], ))
  db.commit()
  return dumps(get_schema_titles(), cls=JsonEncoder)



############################# ALERTS #############################
# def get_alerts_select(code):
#   return db.all("SELECT id, title FROM alerts WHERE code ~ %s;", (code, ), as_dict=True)


@pgvega.route('/admin-reports/alerts')
@login_required
@check_admin
@db.wrapper
async def alerts():
  return await render_template('templates/alerts.html', title="Alertas")


'''
def select_alerts_data(dbObj, rq):
  crons = dbObj.getRow("SELECT ARRAY_AGG(cron) FROM crons;")
  querys = dbObj.getRow("SELECT ARRAY_AGG(code) FROM querys WHERE code LIKE 'alerts_%';")
  return {"crons":crons[0] if crons else [],
          "querys":querys[0] if querys else [],
          #"phones":dbObj.getRows("""
          #           SELECT (SELECT persona FROM personas WHERE id=pt.persona_id) AS persona,
          #                  ARRAY_AGG(telefono || '_' || nota)
          #           FROM personas_telefonos pt GROUP BY persona_id ORDER BY persona;"""),
          "workers":dbObj.getRow("SELECT ARRAY_AGG(worker) FROM workers;")[0]}


def select_alerts(dbObj, rq):
  return dbObj.getRows("""SELECT id,
                                 (SELECT cron FROM crons WHERE id=a.cron_id),
                                 (SELECT code FROM querys WHERE id=a.query_id),
                                 (SELECT ARRAY_AGG(target) FROM alerts_targets
                                  WHERE alert_id=a.id)
                          FROM alerts a WHERE type=%s;""", (rq['type'], ))


def insert_alert(dbObj, rq):
  a_id = dbObj.getRow("""INSERT INTO alerts
                         VALUES(DEFAULT, (SELECT id FROM crons WHERE cron=%s),
                                (SELECT id FROM querys WHERE code=%s), %s)
                         RETURNING id;""", (rq['cron'], rq['query'], rq['type']))[0]
  items = loads(rq['items'])
  for item in items:
    dbObj.execute("INSERT INTO alerts_targets VALUES(DEFAULT, %s, %s);", (a_id, item))
  return select_alerts(dbObj, rq)


def delete_alert(dbObj, rq):
  dbObj.execute("DELETE FROM alerts WHERE id=%s;", (rq['id'], ))
  return select_alerts(dbObj, rq)


# TODO on close notify INSERT INTO alerts_done
'''

############################# CRONS #############################
#def insert_cron(dbObj, rq):
#  dbObj.execute("INSERT INTO crons VALUES(DEFAULT, %s);", (rq['cron'], ))
#  '''
#  from crontab import CronTab
#
#  cron = CronTab()
#  cron.new(command='/bin/speaker-test -t wav -f 1000 -l 1')
#  cron.write()
#
#  cron.remove_all()
#  for job in cron: print(job)
#  '''
#  return select_crons(dbObj, rq)
#
#
#def delete_cron(dbObj, rq):
#  dbObj.execute("DELETE FROM crons WHERE cron=%s;", (rq['cron'], ))
#  return select_crons(dbObj, rq)
#
#

'''
# from email.mime.application import MIMEApplication
# from email.mime.multipart import MIMEMultipart
# from email.mime.text import MIMEText
# from smtplib import SMTP

#def print_email(dbObj, rq):
#  email_oficina = dbObj.getRow("""
#     SELECT (SELECT email_oficina FROM personas WHERE id=documentos.persona_id) AS persona
#     FROM documentos WHERE id=%s""", (rq['a_id'], ))[0]
#  if not email_oficina:
#    raise Exception('Email oficina no esta definido!')
#  activity = dbObj.getRow("SELECT activity FROM public.activities WHERE id=%s;",
#                          (sub('activity_', '', rq['schema']), ))[0]
#  pdf_data = print_pdf(dbObj, rq)
#  msg = MIMEMultipart()
#  msg['Subject'] = '%s' % activity
#  msg['From'] = 'contabilidad@granjalibre.com'
#  msg['To'] = email_oficina
#  msg.attach(MIMEText("""
#***  No conteste a este mensaje ya que no recibirá ninguna respuesta.  ***
#Muchas Gracias.
#  """, 'plain'))
#  pdf = MIMEApplication(pdf_data, _subtype='pdf')
#  pdf.add_header('Content-Disposition', 'attachment', filename='fct.pdf')
#  msg.attach(pdf)
#  s = SMTP('localhost')
#  s.send_message(msg)
#  s.quit()
'''

app/pgvega/templates/alerts.html
{% extends "base.html" %}
{% block title %}Alertas{% endblock %}
{% block body %}
<div>
  <table id="crons_table" class="table table-striped">
    <caption class="row">
      <h2 style="display:inline;">CRONS</h2>
      <select id="crons_select" class="col-auto form-select" style="width:300px;"></select>
      <!--button class="btn btn-danger">borrar</button>
      <button class="btn btn-primary">ingresar</button-->
    </caption>
    <thead>
      <tr>
        <th><input type="text" class="form-control" placeholder="minutes . . ." /></th>
        <th><input type="text" class="form-control" placeholder="hours . . ." /></th>
        <th><input type="text" class="form-control" placeholder="days . . ." /></th>
        <th><input type="text" class="form-control" placeholder="months . . ." /></th>
        <th><input type="text" class="form-control" placeholder="weekdays . . ." /></th>
      </tr>
      <tr>
        <td>minutes: <strong>0-59</strong></td>
        <td>hours: <strong>0-23</strong></td>
        <td>days: <strong>1-31</strong></td>
        <td>months: <strong>1-12</strong></td>
        <td>weekdays: <strong>0-6</strong> (0=sunday)</td>
      </tr>
    </thead>
    <tbody>
      <tr><th>*</th><td colspan="4">every value</td></tr>
      <tr><th>,</th><td colspan="4">list of values (0,30 = the 0 and 30th minute)</td></tr>
      <tr><th>-</th><td colspan="4">range of values (0-5 = minutes 0,1,2,3,4,5)</td></tr>
      <tr><th>/</th><td colspan="4">step values (*/5 = every 5 minutes; 0-30/2 = every 2 minutes between 0 abd 30 minutes)</td></tr>
    </tbody>
  </table>
  <!-- Nav tabs -->
  <ul id="alerts_nav" class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" data-bs-toggle="tab" href="#alerts_sms" role="tab" aria-controls="sms" aria-selected="true">SMS</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" data-bs-toggle="tab" href="#alerts_calendar" role="tab" aria-controls="calendar" aria-selected="false">Calendario</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" data-bs-toggle="tab" href="#alerts_notify" role="tab" aria-controls="notify" aria-selected="false">Notificaciones</a>
    </li>
    <li>&nbsp;<button class="btn btn-info">ver</button></li>
  </ul>
  <!-- Tab panels -->
  <div id="alerts_tabs" class="tab-content">
    <div class="tab-pane show active" id="alerts_sms" role="tabpanel" aria-labelledby="sms-tab">
      <br>
      <table class="table table-striped">
        <thead>
          <form action="#" style="display:table-row;">
            <td width="200"><select class="form-select" name="cron"></select></td>
            <td width="200"><select class="form-select" name="query"></select></td>
            <td width="600"><select class="selectpicker form-select" name="phones" title="telefonos . . ." data-icon-base="fa" data-tick-icon="fa-check" multiple></select></td>
            <td><input type="submit" class="btn btn-primary" value="ingresar" /></td>
          </form>
        </thead>
        <tbody></tbody>
      </table>
    </div>
    <div class="tab-pane" id="alerts_calendar" role="tabpanel" aria-labelledby="calendar-tab">
      <br>
      <table class="table table-striped">
        <thead>
          <form action="#" style="display:table-row;">
            <td width="200"><select class="form-select" name="cron"></select></td>
            <td width="200"><select class="form-select" name="query"></select></td>
            <td width="600"><select class="selectpicker form-select" name="workers" title="usuarios . . ." data-icon-base="fa" data-tick-icon="fa-check" multiple></select></td>
            <td><input type="submit" class="btn btn-primary" value="ingresar" /></td>
          </form>
        </thead>
        <tbody></tbody>
      </table>
    </div>
    <div class="tab-pane" id="alerts_notify" role="tabpanel" aria-labelledby="notify-tab">
      <br>
      <table class="table table-striped">
        <thead>
          <form action="#" style="display:table-row;">
            <td width="200"><select class="form-select" name="cron"></select></td>
            <td width="200"><select class="form-select" name="query"></select></td>
            <td width="600"><select class="selectpicker form-select" name="workers" title="usuarios . . ." data-icon-base="fa" data-tick-icon="fa-check" multiple></select></td>
            <td><input type="submit" class="btn btn-primary" value="ingresar" /></td>
          </form>
        </thead>
        <tbody></tbody>
      </table>
    </div>
  </div>

</div>
{% endblock %}

{% block script %}
<script>
$("#crons_select").change(function(){
  var values = $(this).val().split(" ");
  $("#crons_table").find("thead input:eq(0)").val(values[0]).end()
                   .find("thead input:eq(1)").val(values[1]).end()
                   .find("thead input:eq(2)").val(values[2]).end()
                   .find("thead input:eq(3)").val(values[3]).end()
                   .find("thead input:eq(4)").val(values[4]);
});

function set_alerts_crons(rs) {
  var rows = ['<option value="">cron . . .</option>'];
  for (var k in rs) rows.push('<option>' + rs[k] + '</option>');
  $("#crons_select").html(rows.join(""));
  $("#alerts_sms table thead select[name='cron']").html(rows.join(""));
  $("#alerts_calendar table thead select[name='cron']").html(rows.join(""));
  $("#alerts_notify table thead select[name='cron']").html(rows.join(""));
}

function set_alerts_querys(rs) {
  var rows = ['<option value="">consulta . . .</option>'];
  for (var k in rs) rows.push('<option>' + rs[k] + '</option>');
  $("#alerts_sms table thead select[name='query']").html(rows.join(""));
  $("#alerts_calendar table thead select[name='query']").html(rows.join(""));
  $("#alerts_notify table thead select[name='query']").html(rows.join(""));
}

function set_alerts_phones(rs) {
  var rows = [];
  for (var k in rs) {
    rows.push('<optgroup label="' + rs[k][0] + '">');
    for (var kk in rs[k][1]) {
      var info = rs[k][1][kk].split('_');
      rows.push('<option data-title="'+info[0]+'" data-subtext="'+info[1]+'">'+info[0]+'</option>');
    }
    rows.push('</optgroup>');
  }
  $("#alerts_sms table thead select[name='phones']").html(rows.join(""));
}

function set_alerts_workers(rs) {
  var rows = '<option>' + rs.join('</option><option>') + '</option>';
  $("#alerts_calendar table thead select[name='workers']").html(rows);
  $("#alerts_notify table thead select[name='workers']").html(rows);
}

function set_alerts_rows(rs) {
  var rows=[], len=rs.length;
  for (var i=0; i<len; ++i) {
    rs[i][3] = rs[i][3].join(", ");
    rows.push('<tr data-id="' + rs[i][0] + '">');
    rows.push('<td>', rs[i].slice(1).join('</td><td>'), '</td>');
    rows.push('<td><button class="btn btn-danger delete_alert">borrar</button></td>');
    rows.push('</tr>');
  }
  return rows.join("");
}

// select_alerts_data
set_alerts_crons({# crons|safe #}[]);
set_alerts_querys({# querys|safe #}[]);
set_alerts_phones({# phones|safe #}[]);
set_alerts_workers({# workers|safe #}[]);
$(".selectpicker").selectpicker("refresh");

$("#alerts_nav button").click(function(){
  var id = $("#alerts_nav li.active a").attr("href"),
      pd = new FormData();
  pd.append("action", "select_alerts");
  pd.append("type", id.replace(/#alerts_/, ''));
/*
  request(db_url, pd, function(rs){
    $(id).find("table tbody").html(set_alerts_rows(rs));
  });
*/
});

$("#alerts_tabs table form").submit(function(){
  var $div = $(this).closest("div.tab-pane"),
      pd = new FormData(this);
  pd.append("action", "insert_alert");
  pd.append("type", $div.attr("id").replace(/alerts_/, ''));
  pd.append("items", JSONfn.stringify($div.find("table thead select.selectpicker").val()));
/*
  request(db_url, pd, function(rs){
    $div.find("table tbody").html(set_alerts_rows(rs));
  });
*/
  return false;
});

$("#alerts_tabs table > tbody").on("click", ".delete_alert",  function(){
  var $tr = $(this).parents("tr"),
      conf = confirm("Desea borrar alerta con consulta: " + $tr.find("td:eq(1)").text() + "?");
  if (conf) {
    var $div = $(this).closest("div.tab-pane"),
        pd = new FormData();
    pd.append("action", "delete_alert");
    pd.append("id", $tr.data("id"));
    pd.append("type", $div.attr("id").replace(/alerts_/, ''));
/*
    request(db_url, pd, function(rs){
      $div.find("table tbody").html(set_alerts_rows(rs));
    });
*/
  }
});
</script>
{% endblock %}

app/pgvega/templates/report.html
{% extends "base.html" %}
{% block title %}Reporte{% endblock %}
{% block body %}

<div id="querys_buttons" class="row buttons"></div>

<div id="querys_content"></div>

<!-- SUBQUERY MODAL -->
<div id="subquery_modal" class="modal fade" role="dialog" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <h3 class="modal-title">Subquery</h3>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button class="btn btn-info xls_subquery">xls</button>
        <button class="btn btn-info print_subquery">imprimir</button>
      </div>
    </div>
  </div>
</div>

<div id="subquery2_modal" class="modal fade" role="dialog" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <h3 class="modal-title">Subquery2</h3>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button class="btn btn-info xls_subquery">xls</button>
        <button class="btn btn-info print_subquery">imprimir</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>{% include("templates/report.js") %}</script>
<script>
// QUERYS TABLE
set_buttons($("#querys_buttons"), {{ data|safe }});

var params = new URLSearchParams(window.location.search);
$("#querys_buttons").find("input, select").each(function(index){
  var name = $(this).attr('name');
  if (params.has(name)) $(this).val(params.get(name));
});

$("#querys_content").data("all_lines", true);
$("#querys_buttons button[name='ver']").click(function(){
  var pd = new FormData(),
      pdf = $(this).data('pdf') == '1',
      $buttons = $(this).parent(),
      $inputs = $buttons.find("input[type=text]:visible, select:visible"),
      params = [];
  $inputs.each(function(index){
    var $input = $(this);
    pd.append($input.attr('name'), $input.val());
    params.push($input.attr('name')+': '+$input.val());
  });
  if (!pdf) {
    request('{{ url_for("pgvega.get_report", code=code) }}', pd, function(rs){  //  + window.location.search
      $("#querys_content").empty();
      set_content($("#querys_content"), rs);
    });
  } else {
    pd.append("params", params.join(", "));
    request_pdf('{{ url_for("pgvega.get_report_pdf", code=code) }}', pd, function(blob, filename){
      downloadPDF(blob, "{{ code }}.pdf");
    });
  }
});
</script>
{% endblock %}

app/pgvega/templates/reports.html
{% extends "base.html" %}
{% block title %}Reportes{% endblock %}
{% block body %}
<div>
  <div style="display: flex; flex-direction: row;">
    <div style="flex: 0 0 auto; width:200px;">
      <h3>TABLES</h3>
      <div style="padding-left:15px; height: 775px; overflow-x: hidden; overflow-y: scroll;">
        <table id="schema_table"><tbody></tbody></table>
      </div>
    </div>
    <div style="flex: 1 1 auto; width:calc(100% - 200px); min-width: 850px;">

      <h3 class="row">
        SQL / JSON&nbsp;
        <select id="querys_saved" class="col-auto form-select" style="width:500px;"></select>&nbsp;
        <input id="query_select" type="button" class="col-auto col-lg-1 btn btn-success" value="select" />
      </h3>
      <div class="panel-container-vertical" style="height: 725px;">
        <!-- variables => %(d1)s = desde, %(d2)s = hasta, %(v)s = valor, %(c)s = moneda -->
        <div id="code-wrapper0" class="panel-top" data-language="sql"
             style="height: 450px; background:#000; caret-color: #fff;">
-- comment
SELECT MIN(id), MAX(id) FROM documents WHERE date>=%(d1)s AND date<=%(d2)s;
        </div>
        <div class="splitter-horizontal"></div>
        <!-- variables => head = encabezado, value = valor, class = clase(subquery, record), foot = pie(sum, avg, min, max, count) -->
        <div id="code-wrapper1" class="panel-bottom" data-language="json"
             style="background:#000; caret-color: #fff;">
[{"type":"table",
  "defs":[{"head":"Min", "foot":"count"},
          {"head":"Max", "class":"subquery"},
          {"head":"Min+Max", "value":"r[0] + r[1]"}]}]
        </div>
      </div>

      <div id="querys_information" class="row" style="margin:10px;">
        <input type="text" class="col-auto form-control" name="code" placeholder="code . . ." style="width:200px;" />&nbsp;
        <input type="text" class="col-auto form-control" name="title" placeholder="title . . ." style="width:300px;" />&nbsp;
        <input type="button" class="col-auto btn btn-primary" value="insert" />&nbsp;
        <input type="button" class="col-auto btn btn-warning" value="update" />&nbsp;
        <input type="button" class="col-auto btn btn-danger" value="delete" />
      </div>

    </div>
  </div>
  <!--div style="width:900px; margin:1px auto;">
    <div id="querys_buttons" class="row"></div>
    <div id="querys_content"></div>
  </div-->
</div>
{% endblock %}

{% block script %}
<!--script>{% include("templates/report.js") %}</script-->
<script>
$(".panel-top").resizable({handleSelector: ".splitter-horizontal", resizeWidth: false});

function array_tree_table(id, tmp, levels) {
  var parents=[0,1], len=tmp.length;
  var rows=["<tr id='"+id+"-1' class='parent'><td class='first'>", tmp[0].join("</td><td>"), "</td></tr>"];
  for (i=1; i<len; ++i){
    var level=parseInt(levels[i], 10);
    parents[level+1] = i+1;
    parents = parents.slice(0, level+2);
    rows.push("<tr id='"+id+"-"+(i+1)+"' class='"+(tmp[i][0].match(/bold/)?'parent ':'')+(level?"child-of-"+id+"-"+parents.slice(-2, -1):'')+"'><td class='first'>", tmp[i].join("</td><td>"), "</td></tr>");
  }
  return rows.join('');
}

///////////// QUERYS /////////////
var flask0=new CodeFlask, flask1=new CodeFlask;
flask0.run("#code-wrapper0", {language: "sql", lineNumbers: true});
flask1.run("#code-wrapper1", {language: "json", lineNumbers: true});

/*
var flask0 = new CodeFlask('#code-wrapper0', {language: 'sql', lineNumbers: true, defaultTheme: false}),
    flask1 = new CodeFlask('#code-wrapper1', {language: 'js', lineNumbers: true, defaultTheme: false});
*/

function set_querys_schema_titles(rs) {
  // SCHEMA
  var schema = rs["schema"], rows = [], levels = [];
  for (var i in schema) {
    var tmp = schema[i]['columns'].split(",");
    rows.push([schema[i]['table']]);
    levels.push(0);
    for (var j in tmp) {
      rows.push([tmp[j]]);
      levels.push(1);    
    }
  }
  $("#schema_table tbody").html(array_tree_table('compSal', rows, levels));
  $("#schema_table").treeTable();
  // TITLES
  var titles = rs["titles"], rows = ['<option value="">Saved Querys . . .</option>'];
  for (var k in titles) {
    rows.push('<option value="'+titles[k]['code']+'">' +
              titles[k]['code'].padEnd(titles[k]['l']+4, '_') + titles[k]['title'] +
              '</option>');
  }
  $("#querys_saved").html(rows.join(""));
}

// QUERYS SAVED
set_querys_schema_titles({{ schema_titles|safe }});

$("#querys_saved").on("change", function(){
  var pd = new FormData(),
      code = $(this).val();
  if (code != "") {
//    pd.append("action", "select_querys_data");
    pd.append("code", code);
    request('{{ url_for("pgvega.get_query_def") }}', pd, function(rs){
      flask0.update(rs[1].replace(/\\\\/g, '\n'));
      flask1.update(rs[2].replace(/\\\\/g, '\n'));
      $("#querys_information").find("input[name='code']").val(rs[3]).end()
                              .find("input[name='title']").val(rs[4]);
    });
  }
});

$("#query_select").click(function(){
  var code = $("#querys_information").find("input[name='code']").val();
  window.location = '{{ url_for("pgvega.get_report", code="") }}' + code;
});

// QUERYS INFORMATION
$("#querys_information input[value='insert']," +
  "#querys_information input[value='update']").click(function(){
  var pd = new FormData(),
      v = $(this).attr("value"),
      $qi = $("#querys_information");
  pd.append("action", v);
  pd.append("query", $.trim($("#code-wrapper0 code").text()).replace(/\n/g, '\\\\'));
  pd.append("defs", $.trim($("#code-wrapper1 code").text()).replace(/\n/g, '\\\\'));
  pd.append("code", $.trim($qi.find("input[name='code']").val()));
  pd.append("title", $.trim($qi.find("input[name='title']").val()));
  request('{{ url_for("pgvega.set_query") }}', pd, set_querys_schema_titles);
});

$("#querys_information input[value='delete']").click(function(){
  var pd = new FormData();
  pd.append("action", "delete");
  pd.append("code", $.trim($("#querys_information input[name='code']").val()));
  request('{{ url_for("pgvega.set_query") }}', pd, set_querys_schema_titles);
});
</script>
{% endblock %}