app/workers_chats/__init__.py
from quart import Blueprint

workers_chats = Blueprint('workers_chats', __name__, template_folder='')

from . import views

app/workers_chats/views.py
from datetime import datetime
from json import dumps, loads
from math import ceil
from quart import current_app, flash, request, render_template, session
from quart_auth import current_user, login_required
from re import sub

from app import db, ws
from . import workers_chats
from ..utils.admin import check_user
from ..utils.utils import escape, unescape  # , JsonEncoder


@workers_chats.route('/workers_chats/chats')
@login_required
@check_user
@db.wrapper
async def get_chats():
  rows = db.all("""SELECT thread_id AS thread, TO_CHAR(inactived, 'YY-MM-DD, HH:MIAM') AS inactived,
                          CASE WHEN tw.friend_id IS NULL THEN 'public' ELSE 'private' END AS type,
                          COALESCE((SELECT worker FROM workers WHERE id=tw.friend_id),
                                   (SELECT title FROM threads WHERE id=tw.thread_id)) AS title,
                          (SELECT COUNT(*) FROM threads_messages
                           WHERE thread_id=tw.thread_id AND created>tw.inactived) AS unread,
                          TO_CHAR(COALESCE((SELECT MAX(created) FROM threads_messages
                            WHERE thread_id=tw.thread_id), created), 'YY-MM-DD, HH:MIAM') AS last
                   FROM threads_workers tw
                   WHERE worker_id=%s AND joined IS TRUE
                   ORDER BY unread DESC, last DESC;""", (await current_user.id, ), as_dict=True)

  return await render_template('templates/chat.html', title='Chats', chats=rows)


@workers_chats.route('/workers_chats/get_chat', methods=['POST'])
@login_required
@check_user
@db.wrapper
async def get_chat():
  rq = await request.form
  rows = db.all("""SELECT 'public' AS type, id, title AS name FROM threads WHERE title ILIKE %s
                   UNION ALL
                   SELECT 'private', id, worker FROM workers WHERE id<>%s AND worker ILIKE %s
                   ORDER BY name ASC LIMIT 20;""",
                ('%%%s%%' % rq['val'], await current_user.id, '%%%s%%' % rq['val']), as_dict=True)
  return dumps(rows)


@workers_chats.route('/workers_chats/set_chat', methods=['POST'])
@login_required
@check_user
@db.wrapper
async def set_chat():
  rq = await request.form
  u_id = await current_user.id
  row = db.one("""SELECT thread_id, joined FROM threads_workers
                  WHERE 'public' = %s AND worker_id=%s AND thread_id=%s OR
                        'private' = %s AND worker_id=%s AND friend_id=%s;""",
               (rq['type'], u_id, rq['id'], rq['type'], u_id, rq['id']))
  if row:
    thread = row[0]
    if rq['type'] == 'block':
      db.execute("UPDATE threads_workers SET blocked=TRUE WHERE thread_id=%s AND friend_id=%s;",
                 (thread, u_id))
    elif rq['type'] == 'unjoin':
      db.execute("UPDATE threads_workers SET joined=FALSE WHERE thread_id=%s AND worker_id=%s;",
                 (thread, u_id))
    elif row[1] is False:
      db.execute("UPDATE threads_workers SET joined=TRUE WHERE thread_id=%s AND worker_id=%s;",
                 (thread, u_id))
  elif rq['type'] == 'public':
    thread = rq['id']
    db.execute("INSERT INTO threads_workers VALUES(DEFAULT, %s, %s, NULL, TRUE, FALSE, NOW(), NOW());",
               (thread, u_id))
  elif rq['type'] == 'private':
    thread = db.one("INSERT INTO threads VALUES(DEFAULT, %s, NULL, NOW()) RETURNING id;",
                    (u_id, ))[0]
    db.execute("INSERT INTO threads_workers VALUES(DEFAULT, %s, %s, %s, TRUE, FALSE, NOW(), NOW());",
               (thread, u_id, rq['id']))
    db.execute("INSERT INTO threads_workers VALUES(DEFAULT, %s, %s, %s, TRUE, FALSE, NOW(), NOW());",
               (thread, rq['id'], u_id))
  db.commit()
  return dumps({"thread": thread})


def check_joined_blocked(thread, user_id):
  rows = db.all("""SELECT id, joined, blocked, worker_id FROM threads_workers
                   WHERE thread_id=%s AND (worker_id=%s OR friend_id=%s);""",
                (thread, user_id, user_id))
  for row in rows:
    if row[1] is False:
      db.execute("UPDATE threads_workers SET joined=TRUE WHERE id=%s;", (row[0], ))
    if row[2] is True:
      if row[3] != user_id:
        db.execute("UPDATE threads_workers SET blocked=FALSE WHERE friend_id=%s;", (row[0], ))
      else:
        raise Exception('Usuario bloqueado!')
  db.commit()


@workers_chats.route('/workers_chats/set_chat_msg', methods=['POST'])
@login_required
@check_user
@db.wrapper
async def set_chat_msg():
  rq = await request.form
  u_id = await current_user.id
  thread = loads(await set_chat())["thread"]  # type = private, public
  check_joined_blocked(thread, u_id)
  db.execute("INSERT INTO threads_messages VALUES (DEFAULT, %s, %s, %s, NOW());",
             (thread, u_id, rq['msg']))
  db.commit()
  return '[]'


@workers_chats.route('/workers_chats/get_chat_data', methods=['POST'])
@login_required
@check_user
@db.wrapper
async def get_chat_data():
  rq = await request.form
  lines = 20
  page = int(rq['page'])
  rows = db.all("""SELECT COUNT(*) OVER(), worker_id,
                          (SELECT worker FROM workers WHERE id=tm.worker_id),
                          message, created
                   FROM threads_messages tm WHERE thread_id=%s
                   ORDER BY created DESC LIMIT %s OFFSET %s;""", (rq['thread'], lines, (page-1)*lines))
  count = rows[0][0] if rows else 0
  if rows:
    rows = [{"action":"active", "thread":rq['thread'], "msg":row[3],
             "dt":row[4].strftime("%Y-%m-%d, %-I:%M%p"),
             "worker":row[2] if row[1] != int(await current_user.id) else ""} for row in rows]
  else:
    rows = []
  return dumps({"rows":rows, "count":count, "page":page, "pages":ceil(count/lines)})  # , cls=JsonEncoder


@workers_chats.websocket('/workers_chats/chat_ws')
@ws.wrapper
async def chat_ws(key, disconnect):
  id = ws.get_id(key)
  thread = sub('_\d+$', '', id)
  user_id = sub('^.*_', '', id)
  schema = session['schema'] if 'schema' in session else 'public'
  if disconnect:
    db.connect(schema)
    db.execute("""UPDATE threads_workers SET inactived=NOW()
                  WHERE thread_id=%s AND worker_id=%s;""", (thread, user_id))
    db.commit()
    db.close()
  else:
    db.connect(schema)
    worker = db.one("SELECT worker FROM workers WHERE id=%s", (user_id, ))[0]
    db.close()
    socket = ws.get_socket(key)
    tz = current_app.config['TIMEZONE']
    # await socket.send(dumps({"action":"joined", "thread":thread, "msg":"", "worker":worker,
    #                          "dt":datetime.now(tz).strftime("%Y-%m-%d, %-I:%M%p")}))
    while True:
      data = await socket.receive()
      msg = sub('[^a-zA-Z0-9 \]\[{}()"'';:,.&|?!~#$%<>=/*+-]+', '-', escape(data))
      db.connect(schema)
      if msg != '**typing**':
        check_joined_blocked(thread, user_id)
        db.execute("INSERT INTO threads_messages VALUES (DEFAULT, %s, %s, %s, NOW());",
                   (thread, user_id, msg))
        db.commit()
      rows = db.all("""SELECT worker_id, (SELECT ARRAY_AGG(thread_id || '_' || worker_id)
                                          FROM threads_workers WHERE worker_id=tw.worker_id) AS others
                       FROM threads_workers tw WHERE thread_id=%s;""", (thread, ), as_dict=True)
      db.close()
      ids = ws.get_ids()
      for row in rows:
        for k, v in ids.items():
          a_id = '%s_%s' % (thread, row['worker_id'])
          if v == a_id and (row['worker_id'] != int(user_id) or msg != '**typing**'):
            a_socket = ws.get_socket(k)
            await a_socket.send(dumps({"action":"active", "thread":thread, "msg":unescape(msg),
                                       "dt":datetime.now(tz).strftime("%Y-%m-%d, %-I:%M%p"),
                                       "worker":worker if row['worker_id'] != int(user_id) else ""}))
          elif v in row['others'] and row['worker_id'] != int(user_id) and msg != '**typing**':
            o_socket = ws.get_socket(k)
            await o_socket.send(dumps({"action":"others", "thread":thread, "msg":"", "dt":"", "worker":""}))

app/workers_chats/templates/chat.html
{% extends "base.html" %}
{% block title %}Chats{% endblock %}
{% block body %}
<div class="row">

  <nav class="navbar navbar-light sticky-top bg-light flex-md-nowrap p-0 shadow">
    <button class="navbar-toggler d-md-none" id="sidebar_btn" type="button"  data-bs-toggle="collapse" data-bs-target="#sidebarChat" aria-controls="sidebarChat" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h4 class="navbar-brand col-auto col-md-3 me-0 px-3">Chats</h4>
    <div class="input-group w-100">
      <input type="text" class="form-control" id="chat_msg" placeholder="mensaje . . ." autocomplete="off">
      <div class="input-group-append">
        <button id="chat_rec_btn" class="btn btn-warning"><i class="fa fa-lg fa-microphone"></i></button>
        <button id="chat_send_btn" class="btn btn-success"><i class="fa fa-lg fa-check"></i></button>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">

      <nav id="sidebarChat" class="col-md-3 col-lg-3 d-md-block bg-light collapse">
        <div class="sidebar-sticky pt-3">
          <div class="input-group">
            <input type="text" class="form-control" id="chat_search" placeholder="buscar . . ." autocomplete="off">
            <div class="input-group-append">
              <button id="chat_search_btn" class="btn btn-success"><i class="fa fa-plus"></i></button>
            </div>
          </div>
          <ul class="nav flex-column" id="chats_list"></ul>
        </div>
      </nav>

      <div class="col-md-9 ms-sm-auto px-md-4">
        <h2 id="chat_title"></h2>
        <div id="chat_div"></div>
        <div style="clear: both;"></div>
        <div id="chat_paginate"></div>
      </div>

    </div>
  </div>

</div>
{% endblock %}

{% block script %}
<script>
///////////////////////////// CHATS /////////////////////////////
function set_item(row){
  return '<li class="nav-item">' +
         '  <a class="nav-link active" id="chat_' + row['thread'] + '" href="#"' +
         '     data-title="' + row['title'] + '"' +
         '     data-type="' + row['type'] + '"' +
         '     data-inactived="' + row['inactived'] + '">' +
         row['title'] +
         ((row['unread'] > 0)?'<span class="badge badge-warning badge-pill">'+ row['unread'] +'</span>':'') +
//         '<span class="text-muted ms-3" style="font-size:1rem">'+ row['last'] +'</span>' +
         '  <i class="fa fa-angle-right fa-lg mt-1 float-end"></i>' +
         '  </a>' +
         '</li>';
}

$("#chats_list").html($.map({{ chats|safe }}, function(row){
  return set_item(row);
}).join(''));

$("#chat_search").typeahead({
  source: function(query, process) {
    var pd = new FormData();
    pd.append("val", query);
    request('{{ url_for("workers_chats.get_chat") }}', pd, process);
  },
  updater: function(item){
    var $input = $("#chat_search");
    $input.data("id", item.id);
    $input.data("name", item.name);
    $input.data("type", item.type);
    return item;
  }
});

$("#chat_search_btn").click(function(ev){
  var $input = $("#chat_search");
  if ($input.val() != $input.data('name')) {
    alert('Error en seleccion!');
  } else {
    var pd = new FormData();
    pd.append('id', $input.data('id'));
    pd.append('type', $input.data('type'));
    request('{{ url_for("workers_chats.set_chat") }}', pd, function(rs){
      $("#chats_list").prepend(set_item({"thread":rs["thread"], "type":rs["type"],
                                         "title":$input.data('name'),
                                         "inactived":"", "unread":0, "last":""}));
      $("#chat_" +rs["thread"]).click();
    });
  }
});

///////////////////////////// CHAT /////////////////////////////
var ws = null;

function set_card(chat_title, worker, msg, dt){
  let card = '';
  if (worker != '') {
    let typing = (msg == '**typing**')?true:false;
    card = '<div class="alert alert-warning w-75 float-start '+ (typing?'typing':'') +'">' +
           ((worker != chat_title)?'<h5>' + worker + '</h5>':'') +
           (typing?'escribiendo . . .':msg) +
           '<span class="float-end text-muted">' + dt + '</span>' +
           '</div>';
  } else {
    card = '<div class="alert alert-success w-75 float-end">' +
           msg +
           '<span class="float-end text-muted">' + dt + '</span>' +
           '</div>';
  }
  return card;
}

$("#chats_list").on('click', 'a.nav-link', function(ev){
  var pd = new FormData(),
      $this = $(this),
      thread = $this.attr('id').replace('chat_', '');

  // TODO active user
  let last = '<span class="text-muted float-end" style="font-size:1rem">ultima vez: '+ $this.data('inactived') +'</span>';
  $("#chat_title").html((($this.data('type')=='private')?last:'') + $this.data('title'));
  $("#chat_div").empty();
  $("#chat_div").data("thread", thread);
  $("#chat_div").data("title", $this.data('title'));
  $("#chat_" + thread + " span.badge").remove();
  if ($("#sidebar_btn").is(':visible')) $("#sidebar_btn").click();

  pd.append('page', 1);
  pd.append('thread', thread);
  request('{{ url_for("workers_chats.get_chat_data") }}', pd, function(rs){

    $("#chat_div").html($.map(rs['rows'], function(row){
      return set_card($this.data('title'), row['worker'], row['msg'], row['dt']);
    }).join(''));
    var page = parseInt(rs['page'], 10);
    $("#chat_paginate").html('<a class="btn btn-warning mb-2 '+ ((page >= rs['pages'])?'disabled':'') +'"'+
                             '   href="#'+ (page+1) +'" role="button">mensajes anteriores</a>');

    if (ws) ws.close();
    let protocol = (location.protocol == 'https:')?'wss':'ws';
    ws = new WebSocket('{{ url_for("workers_chats.chat_ws") }}'.replace(/^ws/, protocol) + '?thread=' + thread);
    ws.onmessage = function (event) {
      let data = JSON.parse(event.data);
      switch (data['action']) {
        case 'joined':
          // TODO
        break;
        case 'active':
          $("#chat_div div.typing").remove();
          $("#chat_div").prepend(set_card($this.data('title'), data['worker'], data['msg'], data['dt']));
        break;
        case 'others':
          let $span = $("#chat_" + data['thread'] + " span.badge");
          $span.text(parseInt($span.text(), 10) + 1);
        break;
      }
    };

  });
});

var timer=null;

function send_msg(){
  if (ws) {
    window.clearTimeout(timer);
    ws.send($.trim($("#chat_msg").val()));
    $("#chat_msg").val('').focus();
  } else {
    alert('Seleccione un Chat!');
  }
}

$("#chat_msg").keydown(function( event ) {
  if (event.which == 13) {
    event.preventDefault();
    send_msg();
  } else if (ws) {
    window.clearTimeout(timer);
    timer = window.setTimeout(function() { ws.send('**typing**'); }, 5000);
  }
});

$("#chat_send_btn").click(function( event ) {
  send_msg();
});

$("#chat_paginate").on("click", "a", function(ev){
  var pd = new FormData(),
      page = $(this).attr("href").replace(/#/, '');
  pd.append('page', page);
  pd.append('thread', $("#chat_div").data("thread"));
  request('{{ url_for("workers_chats.get_chat_data") }}', pd, function(rs){
    $("#chat_div").append($.map(rs['rows'], function(row){
      return set_card($("#chat_div").data("title"), row['worker'], row['msg'], row['dt']);
    }).join(''));
    var page = parseInt(rs['page'], 10);
    $("#chat_paginate").html('<a class="btn btn-warning mb-2 '+ ((page >= rs['pages'])?'disabled':'') +'"'+
                             '   href="#'+ (page+1) +'" role="button">mensajes anteriores</a>');
  });
});
</script>
{% endblock %}